[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gstd.workspace = true
sails-rs.workspace = true

[dev-dependencies]
application_builder.workspace = true
tokio.workspace = true
sails-rs = { workspace = true, features = ["gtest"] }
